module.exports = {
"png alpha transparency" : "png-alpha",
"animated png (apng)" : "apng",
"video element" : "video",
"audio element" : "audio",
"contenteditable attribute (basic support)" : "contenteditable",
"drag and drop" : "dragndrop",
"internationalization api" : "internationalization",
"queryselector/queryselectorall" : "queryselector",
"getelementsbyclassname" : "getelementsbyclassname",
"html5 form features" : "forms",
"new semantic elements" : "html5semantic",
"css line-clamp" : "css-line-clamp",
"offline web applications" : "offline-apps",
"web workers" : "webworkers",
"@font-face web fonts" : "fontface",
"eot - embedded opentype fonts" : "eot",
"woff - web open font format" : "woff",
"css3 multiple backgrounds" : "multibackgrounds",
"css3 border images" : "border-image",
"css3 background-image options" : "background-img-opts",
"css table display" : "css-table",
"css generated content for pseudo-elements" : "css-gencontent",
"css position:fixed" : "css-fixed",
"beacon api" : "beacon",
"hashchange event" : "hashchange",
"css 2.1 selectors" : "css-sel2",
"css3 selectors" : "css-sel3",
"css3 text-shadow" : "css-textshadow",
"css3 box-shadow" : "css-boxshadow",
"css3 colors" : "css3-colors",
"css3 box-sizing" : "css3-boxsizing",
"css3 media queries" : "css-mediaqueries",
"css3 multiple column layout" : "multicolumn",
"css3 border-radius (rounded corners)" : "border-radius",
"css3 2d transforms" : "transforms2d",
"ecmascript 5 strict mode" : "use-strict",
"window.devicepixelratio" : "devicepixelratio",
"css3 3d transforms" : "transforms3d",
"shared web workers" : "sharedworkers",
"css hyphenation" : "css-hyphens",
"css3 transitions" : "css-transitions",
"css font-feature-settings" : "font-feature",
"css animation" : "css-animation",
"css gradients" : "css-gradients",
"css canvas drawings" : "css-canvas",
"css reflections" : "css-reflections",
"css masks" : "css-masks",
"basic console logging functions" : "console-basic",
"svg (basic support)" : "svg",
"svg in css backgrounds" : "svg-css",
"svg smil animation" : "svg-smil",
"svg fonts" : "svg-fonts",
"svg filters" : "svg-filters",
"svg effects for html" : "svg-html",
"inline svg in html5" : "svg-html5",
"canvas (basic support)" : "canvas",
"text api for canvas" : "canvas-text",
"web storage - name/value pairs" : "namevalue-storage",
"web sql database" : "sql-storage",
"indexeddb" : "indexeddb",
"online/offline status" : "online-status",
"server-sent events" : "eventsource",
"cross-document messaging" : "x-doc-messaging",
"server name indication" : "sni",
"data uris" : "datauri",
"wav audio format" : "wav",
"mathml" : "mathml",
"css feature queries" : "css-featurequeries",
"xhtml served as application/xhtml+xml" : "xhtml",
"xhtml+smil animation" : "xhtmlsmil",
"wai-aria accessibility features" : "wai-aria",
"geolocation" : "geolocation",
"flexible box layout module" : "flexbox",
"webgl - 3d canvas graphics" : "webgl",
"file api" : "fileapi",
"shadow dom" : "shadowdom",
"web sockets" : "websockets",
"hidden attribute" : "hidden",
"async attribute for external scripts" : "script-async",
"media source extensions" : "mediasource",
"cross-origin resource sharing" : "cors",
"css backdrop filter" : "css-backdrop-filter",
"calc() as css unit value" : "calc",
"document object model range" : "dom-range",
"ruby annotation" : "ruby",
"css3 opacity" : "css-opacity",
"form validation" : "form-validation",
"session history management" : "history",
"json parsing" : "json",
"classlist (domtokenlist)" : "classlist",
"css3 text-overflow" : "text-overflow",
"webm video format" : "webm",
"mpeg-4/h.264 video format" : "mpeg4",
"ogg/theora video format" : "ogv",
"css3 overflow-wrap" : "wordwrap",
"pointerlock api" : "pointerlock",
"css3 object-fit/object-position" : "object-fit",
"xmlhttprequest advanced features" : "xhr2",
"css min/max-width/height" : "minmaxwh",
"details & summary elements" : "details",
"css text-stroke" : "text-stroke",
"css inline-block" : "inline-block",
"web notifications" : "notifications",
"getusermedia/stream api" : "stream",
"svg in html img element" : "svg-img",
"datalist element" : "datalist",
"dataset & data-* attributes" : "dataset",
"css grid layout" : "css-grid",
"toolbar/context menu" : "menu",
"css zoom" : "css-zoom",
"rem (root em) units" : "rem",
"ttf/otf - truetype and opentype font support" : "ttf",
"touch events" : "touch",
"matches() dom method" : "matchesselector",
"css pointer-events (for html)" : "pointer-events",
"blob constructing" : "blobbuilder",
"filereader api" : "filereader",
"filesystem & filewriter api" : "filesystem",
"blob urls" : "bloburls",
"rellist (domtokenlist)" : "rellist",
"typed arrays" : "typedarrays",
"deviceorientation & devicemotion events" : "deviceorientation",
"defer attribute for external scripts" : "script-defer",
"navigation timing api" : "nav-timing",
"web audio api" : "audio-api",
"css regions" : "css-regions",
"spellcheck attribute" : "spellcheck-attribute",
"full screen api" : "fullscreen",
"css exclusions level 1" : "css-exclusions",
"requestanimationframe" : "requestanimationframe",
"range input type" : "input-range",
"matchmedia" : "matchmedia",
"date and time input types" : "input-datetime",
"document.execcommand()" : "document-execcommand",
"color input type" : "input-color",
"number input type" : "input-number",
"element.getboundingclientrect()" : "getboundingclientrect",
"sandbox attribute for iframes" : "iframe-sandbox",
"css counters" : "css-counters",
"css resize property" : "css-resize",
"input placeholder attribute" : "input-placeholder",
"spdy protocol" : "spdy",
"css repeating gradients" : "css-repeating-gradients",
"css filter effects" : "css-filters",
"getcomputedstyle" : "getcomputedstyle",
"mp3 audio format" : "mp3",
"css3 word-break" : "word-break",
"viewport units: vw, vh, vmin, vmax" : "viewport-units",
"content security policy 1.0" : "contentsecuritypolicy",
"page visibility" : "pagevisibility",
"strict transport security" : "stricttransportsecurity",
"scoped css" : "style-scoped",
"svg fragment identifiers" : "svg-fragment",
"css outline" : "outline",
"download attribute" : "download",
"pointer events" : "pointer",
"css user-select: none" : "user-select-none",
"accept attribute for file input" : "input-file-accept",
"webp image format" : "webp",
"autocomplete attribute: on & off values" : "input-autocomplete-onoff",
"intrinsic & extrinsic sizing" : "intrinsic-width",
"web cryptography" : "cryptography",
"html templates" : "template",
"opus" : "opus",
"jpeg xr image format" : "jpegxr",
"channel messaging" : "channel-messaging",
"css3 tab-size" : "css3-tabsize",
"mutation observer" : "mutationobserver",
"::selection css pseudo-element" : "css-selection",
"::placeholder css pseudo-element" : "css-placeholder",
"css device adaptation" : "css-deviceadaptation",
"text-emphasis styling" : "text-emphasis",
"web midi api" : "midi",
"canvas blend modes" : "canvas-blending",
"clipboard api" : "clipboard",
"webrtc peer-to-peer connections" : "rtcpeerconnection",
"css3 cursors (original values)" : "css3-cursors",
"css3 cursors: zoom-in & zoom-out" : "css3-cursors-newer",
"webvtt - web video text tracks" : "webvtt",
"promises" : "promises",
"css position:sticky" : "css-sticky",
"dialog element" : "dialog",
"css variables (custom properties)" : "css-variables",
"vibration api" : "vibration",
"css background-blend-mode" : "css-backgroundblendmode",
"blending of html/svg elements" : "css-mixblendmode",
"speech recognition api" : "speech-recognition",
"high resolution time api" : "high-resolution-time",
"battery status api" : "battery-status",
"service workers" : "serviceworkers",
"text-decoration styling" : "text-decoration",
"srcdoc attribute for iframes" : "iframe-srcdoc",
"speech synthesis api" : "speech-synthesis",
"user timing api" : "user-timing",
"srcset attribute" : "srcset",
"ambient light api" : "ambient-light",
"css will-change property" : "will-change",
"css shapes level 1" : "css-shapes",
"domcontentloaded" : "domcontentloaded",
"proximity api" : "proximity",
"improved kerning pairs & ligatures" : "kerning-pairs-ligatures",
"seamless attribute for iframes" : "iframe-seamless",
"css3 image-orientation" : "css-image-orientation",
"picture element" : "picture",
"woff 2.0 - web open font format" : "woff2",
"css text-size-adjust" : "text-size-adjust",
"web animations api" : "web-animation",
"resource timing" : "resource-timing",
"custom elements" : "custom-elements",
"html imports" : "imports",
"multiple file selection" : "input-file-multiple",
"base64 encoding and decoding" : "atob-btoa",
"css appearance" : "css-appearance",
"object rtc (ortc) api for webrtc" : "objectrtc",
"css background-position edge offsets" : "css-background-offsets",
"css.supports() api" : "css-supports-api",
"css touch-action property" : "css-touch-action",
"autofocus attribute" : "autofocus",
"css clip-path property" : "css-clip-path",
"crypto.getrandomvalues()" : "getrandomvalues",
"screen orientation" : "screen-orientation",
"css font loading" : "font-loading",
"font unicode-range subsetting" : "font-unicode-range",
"gamepad api" : "gamepad",
"css font-stretch" : "css-font-stretch",
"css font-size-adjust" : "font-size-adjust",
"png favicons" : "link-icon-png",
"svg favicons" : "link-icon-svg",
"media queries: resolution feature" : "css-media-resolution",
"dom parsing and serialization" : "xml-serializer",
"css image-set" : "css-image-set",
"css box-decoration-break" : "css-boxdecorationbreak",
"object.observe data binding" : "object-observe",
"css counter styles" : "css-at-counter-style",
"css page-break properties" : "css-page-break",
":placeholder-shown css pseudo-class" : "css-placeholder-shown",
"broadcastchannel" : "broadcastchannel",
"crisp edges/pixelated images" : "css-crisp-edges",
"css3 text-align-last" : "css-text-align-last",
"css logical properties" : "css-logical-props",
"fetch" : "fetch",
"referrer policy" : "referrer-policy",
"css background-attachment" : "background-attachment",
"css currentcolor value" : "currentcolor",
"pattern attribute for input fields" : "input-pattern",
"custom protocol handling" : "registerprotocolhandler",
"css scroll snap points" : "css-snappoints",
"minimum length attribute for input fields" : "input-minlength",
"media queries: interaction media features" : "css-media-interaction",
"input method editor api" : "ime",
"css font-smooth" : "font-smooth",
"audio tracks" : "audiotracks",
"video tracks" : "videotracks",
"content security policy level 2" : "contentsecuritypolicy2",
"permissions api" : "permissions-api",
"http/2 protocol" : "http2",
"css3 font-kerning" : "font-kerning",
"jpeg 2000 image format" : "jpeg2000",
"upgrade insecure requests" : "upgradeinsecurerequests",
"public key pinning" : "publickeypinning",
"email, telephone & url input types" : "input-email-tel-url",
"disabled attribute of the fieldset element" : "fieldset-disabled",
"css font-variant-alternates" : "font-variant-alternates",
"form attribute" : "form-attribute",
"ecmascript 5" : "es5",
"pagetransitionevent" : "page-transition-events",
"ogg vorbis audio format" : "ogg-vorbis",
"meter element" : "meter",
"progress element" : "progress",
"css filter() function" : "css-filter-function",
"css element() function" : "css-element-function",
"fido u2f api" : "u2f",
"aac audio file format" : "aac",
"resource hints: prefetch" : "link-rel-prefetch",
"reversed attribute of ordered lists" : "ol-reversed",
"::first-letter css pseudo-element selector" : "css-first-letter",
"wbr (word break opportunity) element" : "wbr-element",
"const" : "const",
"css all property" : "css-all",
"css initial value" : "css-initial-value",
"letter-spacing css property" : "css-letter-spacing",
"css unset value" : "css-unset-value",
"element.insertadjacenthtml()" : "insertadjacenthtml",
"let" : "let",
"arrow functions" : "arrow-functions",
"asm.js" : "asmjs",
"resource hints: lazyload" : "lazyload",
"resource hints: dns-prefetch" : "link-rel-dns-prefetch",
"resource hints: prerender" : "link-rel-prerender",
"rest parameters" : "rest-parameters",
"css cross-fade function" : "css-cross-fade",
"css writing-mode property" : "css-writing-mode",
"customevent" : "customevent",
"node.textcontent" : "textcontent",
"eventtarget.addeventlistener()" : "addeventlistener",
"eventtarget.dispatchevent" : "dispatchevent",
"document.head" : "documenthead",
"node.innertext" : "innertext",
"client hints: dpr, width, viewport-width" : "client-hints-dpr-width-viewport",
"resource hints: preconnect" : "link-rel-preconnect",
"network information api" : "netinfo",
"efficient script yielding: setimmediate()" : "setimmediate",
"es6 number" : "es6-number",
"maxlength attribute for input and textarea elements" : "maxlength",
"proxy object" : "proxy",
"keyboardevent.which" : "keyboardevent-which",
"keyboardevent.charcode" : "keyboardevent-charcode",
"keyboardevent.code" : "keyboardevent-code",
"keyboardevent.location" : "keyboardevent-location",
"keyboardevent.getmodifierstate()" : "keyboardevent-getmodifierstate",
"keyboardevent.key" : "keyboardevent-key",
"brotli accept-encoding/content-encoding" : "brotli",
"element.closest()" : "element-closest",
"input event" : "input-event",
"search input type" : "input-search",
"css motion path" : "css-motion-paths",
"cssom scroll-behavior" : "css-scroll-behavior",
"subresource integrity" : "subresource-integrity",
":in-range and :out-of-range css pseudo-classes" : "css-in-out-of-range",
"push api" : "push-api",
"background-position-x & background-position-y" : "background-position-x-y",
"css revert value" : "css-revert-value",
"css widows & orphans" : "css-widows-orphans",
"web bluetooth" : "web-bluetooth",
"scrollintoview" : "scrollintoview",
"selector list argument of :nth-child and :nth-last-child css pseudo-classes" : "css-nth-child-of",
"focusin & focusout events" : "focusin-focusout-events",
":matches() css pseudo-class" : "css-matches-pseudo",
"rel=noopener" : "rel-noopener",
"css text-justify" : "css-text-justify",
"css scrollbar styling" : "css-scrollbar",
"resource hints: preload" : "link-rel-preload",
"case-insensitive css attribute selectors" : "css-case-insensitive",
":default css pseudo-class" : "css-default-pseudo",
":optional css pseudo-class" : "css-optional-pseudo",
":indeterminate css pseudo-class" : "css-indeterminate-pseudo",
"webgl 2.0" : "webgl2",
"document.currentscript" : "document-currentscript",
"explicit descendant combinator >>" : "css-descendant-gtgt",
":has() css relational pseudo-class" : "css-has",
"selector list argument of :not()" : "css-not-sel-list"
};