module.exports = {
"png alpha transparency" : "png-alpha",
"png alpha" : "png-alpha",
"animated png apng" : "apng",
"apng" : "apng",
"video element" : "video",
"video" : "video",
"audio element" : "audio",
"audio" : "audio",
"contenteditable attribute basic support" : "contenteditable",
"contenteditable" : "contenteditable",
"drag and drop" : "dragndrop",
"dragndrop" : "dragndrop",
"internationalization api" : "internationalization",
"internationalization" : "internationalization",
"queryselector queryselectorall" : "queryselector",
"queryselector" : "queryselector",
"getelementsbyclassname" : "getelementsbyclassname",
"html5 form features" : "forms",
"forms" : "forms",
"new semantic elements" : "html5semantic",
"html5semantic" : "html5semantic",
"css line clamp" : "css-line-clamp",
"offline web applications" : "offline-apps",
"offline apps" : "offline-apps",
"web workers" : "webworkers",
"webworkers" : "webworkers",
"font face web fonts" : "fontface",
"fontface" : "fontface",
"eot embedded opentype fonts" : "eot",
"eot" : "eot",
"woff web open font format" : "woff",
"woff" : "woff",
"css3 multiple backgrounds" : "multibackgrounds",
"multibackgrounds" : "multibackgrounds",
"css3 border images" : "border-image",
"border image" : "border-image",
"css3 background image options" : "background-img-opts",
"background img opts" : "background-img-opts",
"css table display" : "css-table",
"css table" : "css-table",
"css generated content for pseudo elements" : "css-gencontent",
"css gencontent" : "css-gencontent",
"css position fixed" : "css-fixed",
"css fixed" : "css-fixed",
"beacon api" : "beacon",
"beacon" : "beacon",
"hashchange event" : "hashchange",
"hashchange" : "hashchange",
"css 2 1 selectors" : "css-sel2",
"css sel2" : "css-sel2",
"css3 selectors" : "css-sel3",
"css sel3" : "css-sel3",
"css3 text shadow" : "css-textshadow",
"css textshadow" : "css-textshadow",
"css3 box shadow" : "css-boxshadow",
"css boxshadow" : "css-boxshadow",
"css3 colors" : "css3-colors",
"css3 box sizing" : "css3-boxsizing",
"css3 boxsizing" : "css3-boxsizing",
"css3 media queries" : "css-mediaqueries",
"css mediaqueries" : "css-mediaqueries",
"css3 multiple column layout" : "multicolumn",
"multicolumn" : "multicolumn",
"css3 border radius rounded corners" : "border-radius",
"border radius" : "border-radius",
"css3 2d transforms" : "transforms2d",
"transforms2d" : "transforms2d",
"ecmascript 5 strict mode" : "use-strict",
"use strict" : "use-strict",
"window devicepixelratio" : "devicepixelratio",
"devicepixelratio" : "devicepixelratio",
"css3 3d transforms" : "transforms3d",
"transforms3d" : "transforms3d",
"shared web workers" : "sharedworkers",
"sharedworkers" : "sharedworkers",
"css hyphenation" : "css-hyphens",
"css hyphens" : "css-hyphens",
"css3 transitions" : "css-transitions",
"css transitions" : "css-transitions",
"css font feature settings" : "font-feature",
"font feature" : "font-feature",
"css animation" : "css-animation",
"css gradients" : "css-gradients",
"css canvas drawings" : "css-canvas",
"css canvas" : "css-canvas",
"css reflections" : "css-reflections",
"css masks" : "css-masks",
"basic console logging functions" : "console-basic",
"console basic" : "console-basic",
"svg basic support" : "svg",
"svg" : "svg",
"svg in css backgrounds" : "svg-css",
"svg css" : "svg-css",
"svg smil animation" : "svg-smil",
"svg smil" : "svg-smil",
"svg fonts" : "svg-fonts",
"svg filters" : "svg-filters",
"svg effects for html" : "svg-html",
"svg html" : "svg-html",
"inline svg in html5" : "svg-html5",
"svg html5" : "svg-html5",
"canvas basic support" : "canvas",
"canvas" : "canvas",
"text api for canvas" : "canvas-text",
"canvas text" : "canvas-text",
"web storage name value pairs" : "namevalue-storage",
"namevalue storage" : "namevalue-storage",
"web sql database" : "sql-storage",
"sql storage" : "sql-storage",
"indexeddb" : "indexeddb",
"online offline status" : "online-status",
"online status" : "online-status",
"server sent events" : "eventsource",
"eventsource" : "eventsource",
"cross document messaging" : "x-doc-messaging",
"x doc messaging" : "x-doc-messaging",
"server name indication" : "sni",
"sni" : "sni",
"data uris" : "datauri",
"datauri" : "datauri",
"wav audio format" : "wav",
"wav" : "wav",
"mathml" : "mathml",
"css feature queries" : "css-featurequeries",
"css featurequeries" : "css-featurequeries",
"xhtml served as application xhtml xml" : "xhtml",
"xhtml" : "xhtml",
"xhtml smil animation" : "xhtmlsmil",
"xhtmlsmil" : "xhtmlsmil",
"wai aria accessibility features" : "wai-aria",
"wai aria" : "wai-aria",
"geolocation" : "geolocation",
"flexible box layout module" : "flexbox",
"flexbox" : "flexbox",
"webgl 3d canvas graphics" : "webgl",
"webgl" : "webgl",
"file api" : "fileapi",
"fileapi" : "fileapi",
"shadow dom v0" : "shadowdom",
"shadowdom" : "shadowdom",
"web sockets" : "websockets",
"websockets" : "websockets",
"hidden attribute" : "hidden",
"hidden" : "hidden",
"async attribute for external scripts" : "script-async",
"script async" : "script-async",
"media source extensions" : "mediasource",
"mediasource" : "mediasource",
"cross origin resource sharing" : "cors",
"cors" : "cors",
"css backdrop filter" : "css-backdrop-filter",
"calc as css unit value" : "calc",
"calc" : "calc",
"document object model range" : "dom-range",
"dom range" : "dom-range",
"ruby annotation" : "ruby",
"ruby" : "ruby",
"css3 opacity" : "css-opacity",
"css opacity" : "css-opacity",
"form validation" : "form-validation",
"session history management" : "history",
"history" : "history",
"json parsing" : "json",
"json" : "json",
"classlist domtokenlist" : "classlist",
"classlist" : "classlist",
"css3 text overflow" : "text-overflow",
"text overflow" : "text-overflow",
"webm video format" : "webm",
"webm" : "webm",
"mpeg 4 h 264 video format" : "mpeg4",
"mpeg4" : "mpeg4",
"ogg theora video format" : "ogv",
"ogv" : "ogv",
"css3 overflow wrap" : "wordwrap",
"wordwrap" : "wordwrap",
"pointerlock api" : "pointerlock",
"pointerlock" : "pointerlock",
"css3 object fit object position" : "object-fit",
"object fit" : "object-fit",
"xmlhttprequest advanced features" : "xhr2",
"xhr2" : "xhr2",
"css min max width height" : "minmaxwh",
"minmaxwh" : "minmaxwh",
"details summary elements" : "details",
"details" : "details",
"css text stroke and text fill" : "text-stroke",
"text stroke" : "text-stroke",
"chacha20 poly1305 cipher suites for tls" : "chacha20-poly1305",
"chacha20 poly1305" : "chacha20-poly1305",
"css inline block" : "inline-block",
"inline block" : "inline-block",
"web notifications" : "notifications",
"notifications" : "notifications",
"getusermedia stream api" : "stream",
"stream" : "stream",
"svg in html img element" : "svg-img",
"svg img" : "svg-img",
"datalist element" : "datalist",
"datalist" : "datalist",
"dataset data attributes" : "dataset",
"dataset" : "dataset",
"css grid layout" : "css-grid",
"css grid" : "css-grid",
"toolbar context menu" : "menu",
"menu" : "menu",
"css zoom" : "css-zoom",
"rem root em units" : "rem",
"rem" : "rem",
"ttf otf truetype and opentype font support" : "ttf",
"ttf" : "ttf",
"touch events" : "touch",
"touch" : "touch",
"matches dom method" : "matchesselector",
"matchesselector" : "matchesselector",
"css pointer events for html" : "pointer-events",
"pointer events" : "pointer-events",
"blob constructing" : "blobbuilder",
"blobbuilder" : "blobbuilder",
"filereader api" : "filereader",
"filereader" : "filereader",
"filesystem filewriter api" : "filesystem",
"filesystem" : "filesystem",
"blob urls" : "bloburls",
"bloburls" : "bloburls",
"rellist domtokenlist" : "rellist",
"rellist" : "rellist",
"typed arrays" : "typedarrays",
"typedarrays" : "typedarrays",
"deviceorientation devicemotion events" : "deviceorientation",
"deviceorientation" : "deviceorientation",
"defer attribute for external scripts" : "script-defer",
"script defer" : "script-defer",
"navigation timing api" : "nav-timing",
"nav timing" : "nav-timing",
"web audio api" : "audio-api",
"audio api" : "audio-api",
"css regions" : "css-regions",
"spellcheck attribute" : "spellcheck-attribute",
"full screen api" : "fullscreen",
"fullscreen" : "fullscreen",
"css exclusions level 1" : "css-exclusions",
"css exclusions" : "css-exclusions",
"requestanimationframe" : "requestanimationframe",
"range input type" : "input-range",
"input range" : "input-range",
"matchmedia" : "matchmedia",
"date and time input types" : "input-datetime",
"input datetime" : "input-datetime",
"document execcommand" : "document-execcommand",
"color input type" : "input-color",
"input color" : "input-color",
"number input type" : "input-number",
"input number" : "input-number",
"element getboundingclientrect" : "getboundingclientrect",
"getboundingclientrect" : "getboundingclientrect",
"sandbox attribute for iframes" : "iframe-sandbox",
"iframe sandbox" : "iframe-sandbox",
"css counters" : "css-counters",
"css resize property" : "css-resize",
"css resize" : "css-resize",
"input placeholder attribute" : "input-placeholder",
"input placeholder" : "input-placeholder",
"spdy protocol" : "spdy",
"spdy" : "spdy",
"css repeating gradients" : "css-repeating-gradients",
"css filter effects" : "css-filters",
"css filters" : "css-filters",
"getcomputedstyle" : "getcomputedstyle",
"mp3 audio format" : "mp3",
"mp3" : "mp3",
"css3 word break" : "word-break",
"word break" : "word-break",
"viewport units vw vh vmin vmax" : "viewport-units",
"viewport units" : "viewport-units",
"content security policy 1 0" : "contentsecuritypolicy",
"contentsecuritypolicy" : "contentsecuritypolicy",
"page visibility" : "pagevisibility",
"pagevisibility" : "pagevisibility",
"strict transport security" : "stricttransportsecurity",
"stricttransportsecurity" : "stricttransportsecurity",
"scoped css" : "style-scoped",
"style scoped" : "style-scoped",
"svg fragment identifiers" : "svg-fragment",
"svg fragment" : "svg-fragment",
"css outline" : "outline",
"outline" : "outline",
"download attribute" : "download",
"download" : "download",
"pointer" : "pointer",
"css user select none" : "user-select-none",
"user select none" : "user-select-none",
"accept attribute for file input" : "input-file-accept",
"input file accept" : "input-file-accept",
"webp image format" : "webp",
"webp" : "webp",
"autocomplete attribute on off values" : "input-autocomplete-onoff",
"input autocomplete onoff" : "input-autocomplete-onoff",
"intrinsic extrinsic sizing" : "intrinsic-width",
"intrinsic width" : "intrinsic-width",
"web cryptography" : "cryptography",
"cryptography" : "cryptography",
"html templates" : "template",
"template" : "template",
"opus" : "opus",
"jpeg xr image format" : "jpegxr",
"jpegxr" : "jpegxr",
"channel messaging" : "channel-messaging",
"css3 tab size" : "css3-tabsize",
"css3 tabsize" : "css3-tabsize",
"mutation observer" : "mutationobserver",
"mutationobserver" : "mutationobserver",
"selection css pseudo element" : "css-selection",
"css selection" : "css-selection",
"placeholder css pseudo element" : "css-placeholder",
"css placeholder" : "css-placeholder",
"css device adaptation" : "css-deviceadaptation",
"css deviceadaptation" : "css-deviceadaptation",
"text emphasis styling" : "text-emphasis",
"text emphasis" : "text-emphasis",
"web midi api" : "midi",
"midi" : "midi",
"canvas blend modes" : "canvas-blending",
"canvas blending" : "canvas-blending",
"clipboard api" : "clipboard",
"clipboard" : "clipboard",
"webrtc peer to peer connections" : "rtcpeerconnection",
"rtcpeerconnection" : "rtcpeerconnection",
"css3 cursors original values" : "css3-cursors",
"css3 cursors" : "css3-cursors",
"css3 cursors zoom in zoom out" : "css3-cursors-newer",
"css3 cursors newer" : "css3-cursors-newer",
"webvtt web video text tracks" : "webvtt",
"webvtt" : "webvtt",
"promises" : "promises",
"css position sticky" : "css-sticky",
"css sticky" : "css-sticky",
"dialog element" : "dialog",
"dialog" : "dialog",
"css variables custom properties" : "css-variables",
"css variables" : "css-variables",
"vibration api" : "vibration",
"vibration" : "vibration",
"css background blend mode" : "css-backgroundblendmode",
"css backgroundblendmode" : "css-backgroundblendmode",
"blending of html svg elements" : "css-mixblendmode",
"css mixblendmode" : "css-mixblendmode",
"speech recognition api" : "speech-recognition",
"speech recognition" : "speech-recognition",
"high resolution time api" : "high-resolution-time",
"high resolution time" : "high-resolution-time",
"battery status api" : "battery-status",
"battery status" : "battery-status",
"service workers" : "serviceworkers",
"serviceworkers" : "serviceworkers",
"text decoration styling" : "text-decoration",
"text decoration" : "text-decoration",
"srcdoc attribute for iframes" : "iframe-srcdoc",
"iframe srcdoc" : "iframe-srcdoc",
"speech synthesis api" : "speech-synthesis",
"speech synthesis" : "speech-synthesis",
"user timing api" : "user-timing",
"user timing" : "user-timing",
"srcset and sizes attributes" : "srcset",
"srcset" : "srcset",
"ambient light api" : "ambient-light",
"ambient light" : "ambient-light",
"css will change property" : "will-change",
"will change" : "will-change",
"css shapes level 1" : "css-shapes",
"css shapes" : "css-shapes",
"domcontentloaded" : "domcontentloaded",
"proximity api" : "proximity",
"proximity" : "proximity",
"improved kerning pairs ligatures" : "kerning-pairs-ligatures",
"kerning pairs ligatures" : "kerning-pairs-ligatures",
"seamless attribute for iframes" : "iframe-seamless",
"iframe seamless" : "iframe-seamless",
"css3 image orientation" : "css-image-orientation",
"css image orientation" : "css-image-orientation",
"picture element" : "picture",
"picture" : "picture",
"woff 2 0 web open font format" : "woff2",
"woff2" : "woff2",
"css text size adjust" : "text-size-adjust",
"text size adjust" : "text-size-adjust",
"web animations api" : "web-animation",
"web animation" : "web-animation",
"resource timing" : "resource-timing",
"custom elements v0" : "custom-elements",
"custom elements" : "custom-elements",
"html imports" : "imports",
"imports" : "imports",
"multiple file selection" : "input-file-multiple",
"input file multiple" : "input-file-multiple",
"base64 encoding and decoding" : "atob-btoa",
"atob btoa" : "atob-btoa",
"css appearance" : "css-appearance",
"object rtc ortc api for webrtc" : "objectrtc",
"objectrtc" : "objectrtc",
"css background position edge offsets" : "css-background-offsets",
"css background offsets" : "css-background-offsets",
"css supports api" : "css-supports-api",
"css touch action property" : "css-touch-action",
"css touch action" : "css-touch-action",
"autofocus attribute" : "autofocus",
"autofocus" : "autofocus",
"css clip path property for html" : "css-clip-path",
"css clip path" : "css-clip-path",
"crypto getrandomvalues" : "getrandomvalues",
"getrandomvalues" : "getrandomvalues",
"screen orientation" : "screen-orientation",
"css font loading" : "font-loading",
"font loading" : "font-loading",
"font unicode range subsetting" : "font-unicode-range",
"font unicode range" : "font-unicode-range",
"gamepad api" : "gamepad",
"gamepad" : "gamepad",
"css font stretch" : "css-font-stretch",
"css font size adjust" : "font-size-adjust",
"font size adjust" : "font-size-adjust",
"png favicons" : "link-icon-png",
"link icon png" : "link-icon-png",
"svg favicons" : "link-icon-svg",
"link icon svg" : "link-icon-svg",
"media queries resolution feature" : "css-media-resolution",
"css media resolution" : "css-media-resolution",
"dom parsing and serialization" : "xml-serializer",
"xml serializer" : "xml-serializer",
"css image set" : "css-image-set",
"css box decoration break" : "css-boxdecorationbreak",
"css boxdecorationbreak" : "css-boxdecorationbreak",
"object observe data binding" : "object-observe",
"object observe" : "object-observe",
"css counter styles" : "css-at-counter-style",
"css at counter style" : "css-at-counter-style",
"css page break properties" : "css-page-break",
"css page break" : "css-page-break",
"placeholder shown css pseudo class" : "css-placeholder-shown",
"css placeholder shown" : "css-placeholder-shown",
"broadcastchannel" : "broadcastchannel",
"crisp edges pixelated images" : "css-crisp-edges",
"css crisp edges" : "css-crisp-edges",
"css3 text align last" : "css-text-align-last",
"css text align last" : "css-text-align-last",
"css logical properties" : "css-logical-props",
"css logical props" : "css-logical-props",
"fetch" : "fetch",
"referrer policy" : "referrer-policy",
"css background attachment" : "background-attachment",
"background attachment" : "background-attachment",
"css currentcolor value" : "currentcolor",
"currentcolor" : "currentcolor",
"pattern attribute for input fields" : "input-pattern",
"input pattern" : "input-pattern",
"custom protocol handling" : "registerprotocolhandler",
"registerprotocolhandler" : "registerprotocolhandler",
"css scroll snap points" : "css-snappoints",
"css snappoints" : "css-snappoints",
"minimum length attribute for input fields" : "input-minlength",
"input minlength" : "input-minlength",
"media queries interaction media features" : "css-media-interaction",
"css media interaction" : "css-media-interaction",
"input method editor api" : "ime",
"ime" : "ime",
"css font smooth" : "font-smooth",
"font smooth" : "font-smooth",
"audio tracks" : "audiotracks",
"audiotracks" : "audiotracks",
"video tracks" : "videotracks",
"videotracks" : "videotracks",
"content security policy level 2" : "contentsecuritypolicy2",
"contentsecuritypolicy2" : "contentsecuritypolicy2",
"permissions api" : "permissions-api",
"http 2 protocol" : "http2",
"http2" : "http2",
"css3 font kerning" : "font-kerning",
"font kerning" : "font-kerning",
"jpeg 2000 image format" : "jpeg2000",
"jpeg2000" : "jpeg2000",
"upgrade insecure requests" : "upgradeinsecurerequests",
"upgradeinsecurerequests" : "upgradeinsecurerequests",
"public key pinning" : "publickeypinning",
"publickeypinning" : "publickeypinning",
"email telephone url input types" : "input-email-tel-url",
"input email tel url" : "input-email-tel-url",
"disabled attribute of the fieldset element" : "fieldset-disabled",
"fieldset disabled" : "fieldset-disabled",
"css font variant alternates" : "font-variant-alternates",
"font variant alternates" : "font-variant-alternates",
"form attribute" : "form-attribute",
"ecmascript 5" : "es5",
"es5" : "es5",
"pagetransitionevent" : "page-transition-events",
"page transition events" : "page-transition-events",
"ogg vorbis audio format" : "ogg-vorbis",
"ogg vorbis" : "ogg-vorbis",
"meter element" : "meter",
"meter" : "meter",
"progress element" : "progress",
"progress" : "progress",
"css filter function" : "css-filter-function",
"css element function" : "css-element-function",
"fido u2f api" : "u2f",
"u2f" : "u2f",
"aac audio file format" : "aac",
"aac" : "aac",
"resource hints prefetch" : "link-rel-prefetch",
"link rel prefetch" : "link-rel-prefetch",
"reversed attribute of ordered lists" : "ol-reversed",
"ol reversed" : "ol-reversed",
"first letter css pseudo element selector" : "css-first-letter",
"css first letter" : "css-first-letter",
"wbr word break opportunity element" : "wbr-element",
"wbr element" : "wbr-element",
"const" : "const",
"css all property" : "css-all",
"css all" : "css-all",
"css initial value" : "css-initial-value",
"letter spacing css property" : "css-letter-spacing",
"css letter spacing" : "css-letter-spacing",
"css unset value" : "css-unset-value",
"element insertadjacenthtml" : "insertadjacenthtml",
"insertadjacenthtml" : "insertadjacenthtml",
"let" : "let",
"arrow functions" : "arrow-functions",
"asm js" : "asmjs",
"asmjs" : "asmjs",
"resource hints lazyload" : "lazyload",
"lazyload" : "lazyload",
"resource hints dns prefetch" : "link-rel-dns-prefetch",
"link rel dns prefetch" : "link-rel-dns-prefetch",
"resource hints prerender" : "link-rel-prerender",
"link rel prerender" : "link-rel-prerender",
"rest parameters" : "rest-parameters",
"css cross fade function" : "css-cross-fade",
"css cross fade" : "css-cross-fade",
"css writing mode property" : "css-writing-mode",
"css writing mode" : "css-writing-mode",
"customevent" : "customevent",
"node textcontent" : "textcontent",
"textcontent" : "textcontent",
"eventtarget addeventlistener" : "addeventlistener",
"addeventlistener" : "addeventlistener",
"eventtarget dispatchevent" : "dispatchevent",
"dispatchevent" : "dispatchevent",
"document head" : "documenthead",
"documenthead" : "documenthead",
"node innertext" : "innertext",
"innertext" : "innertext",
"client hints dpr width viewport width" : "client-hints-dpr-width-viewport",
"client hints dpr width viewport" : "client-hints-dpr-width-viewport",
"resource hints preconnect" : "link-rel-preconnect",
"link rel preconnect" : "link-rel-preconnect",
"network information api" : "netinfo",
"netinfo" : "netinfo",
"efficient script yielding setimmediate" : "setimmediate",
"setimmediate" : "setimmediate",
"es6 number" : "es6-number",
"maxlength attribute for input and textarea elements" : "maxlength",
"maxlength" : "maxlength",
"proxy object" : "proxy",
"proxy" : "proxy",
"keyboardevent which" : "keyboardevent-which",
"keyboardevent charcode" : "keyboardevent-charcode",
"keyboardevent code" : "keyboardevent-code",
"keyboardevent location" : "keyboardevent-location",
"keyboardevent getmodifierstate" : "keyboardevent-getmodifierstate",
"keyboardevent key" : "keyboardevent-key",
"brotli accept encoding content encoding" : "brotli",
"brotli" : "brotli",
"element closest" : "element-closest",
"input event" : "input-event",
"search input type" : "input-search",
"input search" : "input-search",
"css motion path" : "css-motion-paths",
"css motion paths" : "css-motion-paths",
"cssom scroll behavior" : "css-scroll-behavior",
"css scroll behavior" : "css-scroll-behavior",
"subresource integrity" : "subresource-integrity",
"custom elements v1" : "custom-elementsv1",
"custom elementsv1" : "custom-elementsv1",
"in range and out of range css pseudo classes" : "css-in-out-of-range",
"css in out of range" : "css-in-out-of-range",
"push api" : "push-api",
"es6 template literals template strings" : "template-literals",
"template literals" : "template-literals",
"flac audio format" : "flac",
"flac" : "flac",
"background position x background position y" : "background-position-x-y",
"background position x y" : "background-position-x-y",
"css revert value" : "css-revert-value",
"css widows orphans" : "css-widows-orphans",
"web bluetooth" : "web-bluetooth",
"scrollintoview" : "scrollintoview",
"selector list argument of nth child and nth last child css pseudo classes" : "css-nth-child-of",
"css nth child of" : "css-nth-child-of",
"focusin focusout events" : "focusin-focusout-events",
"matches css pseudo class" : "css-matches-pseudo",
"css matches pseudo" : "css-matches-pseudo",
"rel noopener" : "rel-noopener",
"css text justify" : "css-text-justify",
"css scrollbar styling" : "css-scrollbar",
"css scrollbar" : "css-scrollbar",
"resource hints preload" : "link-rel-preload",
"link rel preload" : "link-rel-preload",
"case insensitive css attribute selectors" : "css-case-insensitive",
"css case insensitive" : "css-case-insensitive",
"default css pseudo class" : "css-default-pseudo",
"css default pseudo" : "css-default-pseudo",
"optional css pseudo class" : "css-optional-pseudo",
"css optional pseudo" : "css-optional-pseudo",
"indeterminate css pseudo class" : "css-indeterminate-pseudo",
"css indeterminate pseudo" : "css-indeterminate-pseudo",
"webgl 2 0" : "webgl2",
"webgl2" : "webgl2",
"css initial letter" : "css-initial-letter",
"document currentscript" : "document-currentscript",
"explicit descendant combinator" : "css-descendant-gtgt",
"css descendant gtgt" : "css-descendant-gtgt",
"samesite cookie attribute" : "same-site-cookie-attribute",
"same site cookie attribute" : "same-site-cookie-attribute",
"has css relational pseudo class" : "css-has",
"css has" : "css-has",
"selector list argument of not" : "css-not-sel-list",
"css not sel list" : "css-not-sel-list",
"credential management api" : "credential-management",
"credential management" : "credential-management",
"dir css pseudo class" : "css-dir-pseudo",
"css dir pseudo" : "css-dir-pseudo",
"focus within css pseudo class" : "css-focus-within",
"css focus within" : "css-focus-within",
"dom manipulation convenience methods" : "dom-manip-convenience",
"dom manip convenience" : "dom-manip-convenience",
"requestidlecallback" : "requestidlecallback",
"element scrollintoviewifneeded" : "scrollintoviewifneeded",
"scrollintoviewifneeded" : "scrollintoviewifneeded",
"css3 attr function" : "css3-attr",
"css3 attr" : "css3-attr",
"sdch accept encoding content encoding" : "sdch",
"sdch" : "sdch",
"css containment" : "css-containment",
"tls 1 2" : "tls1-2",
"tls1 2" : "tls1-2",
"tls 1 1" : "tls1-1",
"tls1 1" : "tls1-1",
"inputmode attribute" : "input-inputmode",
"input inputmode" : "input-inputmode",
"ch character unit" : "ch-unit",
"ch unit" : "ch-unit",
"naturalwidth naturalheight image properties" : "img-naturalwidth-naturalheight",
"img naturalwidth naturalheight" : "img-naturalwidth-naturalheight",
"filereadersync" : "filereadersync",
"mediarecorder api" : "mediarecorder",
"mediarecorder" : "mediarecorder",
"readonly attribute of input and textarea elements" : "readonly-attr",
"readonly attr" : "readonly-attr",
"x frame options http header" : "x-frame-options",
"x frame options" : "x-frame-options",
"indeterminate checkbox" : "indeterminate-checkbox",
"tabindex global attribute" : "tabindex-attr",
"tabindex attr" : "tabindex-attr",
"textencoder textdecoder" : "textencoder",
"textencoder" : "textencoder",
"document elementfrompoint" : "element-from-point",
"element from point" : "element-from-point",
"element insertadjacentelement element insertadjacenttext" : "insert-adjacent",
"insert adjacent" : "insert-adjacent",
"once event listener option" : "once-event-listener",
"once event listener" : "once-event-listener",
"passive event listeners" : "passive-event-listener",
"passive event listener" : "passive-event-listener",
"selection api" : "selection-api",
"payment request api" : "payment-request",
"payment request" : "payment-request",
"shadow dom v1" : "shadowdomv1",
"shadowdomv1" : "shadowdomv1",
"urlsearchparams" : "urlsearchparams",
"css font rendering controls" : "css-font-rendering-controls",
"webassembly" : "wasm",
"wasm" : "wasm",
"css paged media page" : "css-paged-media",
"css paged media" : "css-paged-media",
"childnode remove" : "childnode-remove",
"css first line pseudo element" : "css-first-line",
"css first line" : "css-first-line",
"mutation events" : "mutation-events",
"web app manifest" : "web-app-manifest",
"node comparedocumentposition" : "comparedocumentposition",
"comparedocumentposition" : "comparedocumentposition",
"http live streaming hls" : "http-live-streaming",
"http live streaming" : "http-live-streaming",
"es6 module" : "es6-module",
"es6 classes" : "es6-class",
"es6 class" : "es6-class",
"ping attribute" : "ping",
"ping" : "ping",
"attributes for form submission" : "form-submit-attributes",
"form submit attributes" : "form-submit-attributes",
"async functions" : "async-functions",
"html media capture" : "html-media-capture",
"css text indent" : "css-text-indent",
"intersectionobserver" : "intersectionobserver",
"css marker pseudo element" : "css-marker-pseudo",
"css marker pseudo" : "css-marker-pseudo",
"url api" : "url",
"url" : "url",
"display flow root" : "flow-root",
"flow root" : "flow-root",
"rrggbbaa hex color notation" : "css-rrggbbaa",
"css rrggbbaa" : "css-rrggbbaa",
"printing events" : "beforeafterprint",
"beforeafterprint" : "beforeafterprint",
"webvr api" : "webvr",
"webvr" : "webvr",
"css apply rule" : "css-apply-rule",
"css hanging punctuation" : "css-hanging-punctuation",
"css background repeat round and space" : "background-repeat-round-space",
"background repeat round space" : "background-repeat-round-space",
"document evaluate xpath" : "document-evaluate-xpath",
"css namespaces" : "css-namespaces"
};